services:
  image-search-1:
    container_name: image-search-1
    image: "image-search:0.0.1"
    build:
      context: services/image_search/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - "./common:/app/common"

  image-search-2:
    container_name: image-search-2
    image: "image-search:0.0.1"
    build:
      context: services/image_search/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - "./common:/app/common"

  embedding-1:
    container_name: embedding-1
    image: "embedding:0.0.1"
    build:
      context: services/real-time_compute_embeddings/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"

  embedding-2:
    container_name: embedding-2
    image: "embedding:0.0.1"
    build:
      context: services/real-time_compute_embeddings/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
      - "8080:81"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
